// Explainer/Story hook packs — one entry per published article, tied 1:1 by slug.
//
// This template exists for ONE reason: to make a Liberian with zero financial
// literacy understand money news, fast. So every entry is built around everyday
// archetypes (market woman, keke driver, susu member, cookshop owner, family
// living on money from abroad, smallholder farmer, small retailer…) and their
// daily life.
//
//   hook       — the scroll-stopper (cover slide).
//   points[i]  — a short, plain takeaway (the "so what"), figure kept exact.
//   bodies[i]  — how it touches a real Liberian's day: WHO it affects and HOW.
//                The body must NOT restate the takeaway in other words — it must
//                add the lived, concrete consequence. That is the whole point.
//
// Every figure is sourced from that one article; bodies add human context and may
// soften a figure with "about/roughly" only when the exact value already appears
// in the entry. Per CLAUDE.md, re-check freshness against live CBL data before
// publishing. House style: docs/social-cards-explainer-house-style.md.

export interface HookEntry {
  /** Published article this hook is derived from — the 1:1 anchor. */
  slug: string;
  /** The article's headline at build time, for traceability in the picker. */
  articleTitle: string;
  /** Plain-language scroll-stopper. */
  hook: string;
  /** Three short takeaway titles, seeded into ex1/2/3Title. */
  points: [string, string, string];
  /** For each point, how it affects a real Liberian's daily life — archetype +
      lived consequence, never a restatement of the takeaway. Seeded into
      ex1/2/3Body, same order as `points`. */
  bodies: [string, string, string];
}

export interface HookGroup {
  category: string;
  hooks: HookEntry[];
}

export const HOOK_BANK: HookGroup[] = [
  {
    category: 'Economy',
    hooks: [
      { slug: 'inflation-cools-to-4-5-but-the-core-tells-a-tougher-story',
        articleTitle: "Inflation Cools to 4.50%, but the Core Tells a Tougher Story",
        hook: 'Prices cooled to 4.50% — but strip out the noise and it’s tougher.',
        points: ['Prices are rising more slowly', 'But the basics still bite', 'Fuel is the one that jumped'],
        bodies: ['For a market woman, prices rose just 4.50% over the year — gentler than 2025’s double-digit climbs.', 'Still, the rice, oil and transport she can’t skip are rising faster than that average lets on.', 'Imported fuel alone jumped 12% in the month, so anything moved by car or keke got dearer fast.'] },
      { slug: 'money-supply-swells-11-while-the-central-bank-holds-steady',
        articleTitle: "Money Supply Swells 11% While the Central Bank Holds Steady",
        hook: 'There’s 11% more money around, yet the Central Bank won’t budge.',
        points: ['More money is moving around', 'Yet rates won’t come down', 'The bank is guarding prices'],
        bodies: ['For a trader, there’s 10.66% more money in the economy than a year ago — more cash changing hands.', 'Even so, the Central Bank held rates at 16.25%, so a cheaper loan isn’t coming yet.', 'It’s watching a money base that grew 31%, because too much too fast pushes prices back up.'] },
      { slug: 'public-debt-climbs-to-us-2-82-billion-as-the-bill-mounts',
        articleTitle: "Public Debt Climbs to US$2.82 Billion as the Bill Mounts",
        hook: 'The country now owes US$2.82 billion — and the bill keeps mounting.',
        points: ['The country owes US$2.82 billion', 'The bill grows every year', 'Most of it is owed abroad'],
        bodies: ['For every citizen, the government has borrowed US$2.82 billion that must be repaid with interest.', 'It climbed 7.15% this year, so more of the budget now goes to old debts instead of services.', 'Nearly 58% is owed to foreign lenders, so a weaker L$ would make repaying it harder.'] },
      { slug: 'the-economy-grew-4-6-in-2025-or-5-1-depending-on-who-s-counting',
        articleTitle: "The Economy Grew 4.6% in 2025 — or 5.1%, Depending on Who's Counting",
        hook: 'Did the economy grow 4.6% or 5.1%? It depends who’s counting.',
        points: ['The economy grew about 4.6%', 'Or 5.1%, depending who counts', 'Worth about US$5.16 billion'],
        bodies: ['For most people it was a steady year — the economy grew 4.6%, its best in three years.', 'The World Bank counts it a touch higher at 5.1%; the gap is just how each measures.', 'Either way the whole economy is now worth around US$5.16 billion.'] },
      { slug: 'liberia-gst-to-vat-transition',
        articleTitle: "VAT Set to Replace GST in Biggest Tax Overhaul in Years",
        hook: 'The tax on nearly everything you buy is being rebuilt from scratch.',
        points: ['The sales tax is being rebuilt', 'It should catch more traders', 'Not raise the rate you pay'],
        bodies: ['For a shopkeeper, the tax added at the till is changing from GST to a new VAT system.', 'It’s built to bring more of the buying-and-selling chain into the net, not to charge you more.', 'Done right the price you pay shouldn’t change — but the paperwork for businesses will grow.'] },
      { slug: 'remittances-reach-us-941m-the-backbone-of-liberia-s-external-accounts',
        articleTitle: "Remittances Reach US$941m, the Backbone of Liberia's External Accounts",
        hook: 'Family abroad sent home US$941 million — the country’s quiet backbone.',
        points: ['Family abroad sent US$941 million', 'The biggest inflow of dollars', 'It holds the L$ steady'],
        bodies: ['For families living on money from abroad, that support added up to US$941 million in a year.', 'US$225 million landed in the last three months alone — real money in real pockets.', 'It’s the single biggest source of dollars, and a big reason the L$ has held steady.'] },
      { slug: 'imports-more-than-doubled-in-march-exposing-a-deep-dependence',
        articleTitle: "Imports More Than Doubled in March, Exposing a Deep Dependence",
        hook: 'Almost everything you buy is imported — and last month that bill doubled.',
        points: ['Almost everything is imported', 'Last month the bill doubled', 'US$2.35 billion for the year'],
        bodies: ['For a shopkeeper, most of what fills the shelves comes from abroad — US$329 million of it in March.', 'That’s more than double the same month last year: a lot of goods chasing limited pockets.', 'Across 2025 the import bill hit US$2.35 billion, showing how much daily life leans on foreign goods.'] },
      { slug: 'services-quietly-remain-the-biggest-engine-of-the-economy',
        articleTitle: "Services Quietly Remain the Biggest Engine of the Economy",
        hook: 'The biggest engine of the economy isn’t the mines — it’s services.',
        points: ['Services are the biggest part', 'Shops, transport, hotels', 'Bigger than mines or farms'],
        bodies: ['For anyone running a shop, taxi or eatery, this is the real engine — US$2.01 billion of the economy.', 'It grew about 7% over the year, faster than farming.', 'Quietly, buying, selling and moving people outweighs both the mines and the farms.'] },
      { slug: 'agriculture-employs-the-most-people-but-grew-the-slowest',
        articleTitle: "Agriculture Employs the Most People but Grew the Slowest",
        hook: 'The work most Liberians do grew the slowest of all last year.',
        points: ['Most people farm', 'But farming grew slowest', 'Just 1.3% last year'],
        bodies: ['For the many families who farm and fish, this is the country’s biggest source of jobs — US$1.40 billion of output.', 'Yet it grew just 1.3% in value, slower than almost everything else.', 'So the work that feeds and employs the most people is falling behind the rest of the economy.'] },
      { slug: 'cement-and-beverages-push-manufacturing-up-9',
        articleTitle: "Cement and Beverages Push Manufacturing Up 9%",
        hook: 'The things we make at home — cement, drinks — pushed factories up 9%.',
        points: ['Home-made goods grew 9%', 'Led by cement and drinks', 'Less need to import'],
        bodies: ['For workers in local factories, output of home-made goods rose about 9% to US$331 million.', 'Cement and bottled drinks did most of the lifting.', 'Every bag and bottle made here is one less that has to be shipped in.'] },
      { slug: 'domestic-food-prices-eased-in-liberia-but-imported-fuel-jumped-in-march',
        articleTitle: "Domestic Food Prices Eased in Liberia, but Imported Fuel Jumped in March",
        hook: 'Home-grown food got cheaper while imported fuel jumped the same month.',
        points: ['Home-grown food got cheaper', 'But imported fuel jumped', 'Your bill depends on which'],
        bodies: ['For a family that eats local rice and cassava, home-grown food eased about 1% over the year.', 'But imported fuel jumped 12% in a single month, lifting anything trucked in.', 'Whether your costs rose comes down to how much you buy local versus imported.'] },
      { slug: 'eating-out-gets-15-pricier-the-fastest-rising-cost-of-all',
        articleTitle: "Eating Out Gets 15% Pricier — the Fastest-Rising Cost of All",
        hook: 'Buying cooked food is where prices are rising fastest of all.',
        points: ['Cooked food costs 15% more', 'The fastest-rising of all', 'A big part of spending'],
        bodies: ['For anyone who buys lunch at a cookshop, prices are up 14.8% in a year.', 'No other everyday cost rose faster.', 'And eating out is a heavy share of what households spend, so the pinch is real.'] },
      { slug: 'keeping-the-lights-on-costs-6-more-this-year',
        articleTitle: "Keeping the Lights On Costs 6% More This Year",
        hook: 'Rent, water and light together cost 6% more — and you can’t skip them.',
        points: ['Rent and light cost 6% more', 'Faster than prices overall', 'And you can’t skip them'],
        bodies: ['For a renting household, shelter, water, light and cooking fuel together cost 6.1% more.', 'That’s faster than prices rose overall.', 'These are bills paid every month no matter what, so the rise squeezes hardest.'] },
      { slug: 'health-care-costs-climb-6-and-families-pay-out-of-pocket',
        articleTitle: "Health-Care Costs Climb 6%, and Families Pay Out of Pocket",
        hook: 'When someone falls sick, the bill is up 6% — and it’s yours to pay.',
        points: ['Care costs 6% more', 'And you pay out of pocket', 'A tenth of the budget'],
        bodies: ['For a family with a sick relative, the cost of care climbed 6.1% over the year.', 'Most of it comes straight from the family’s pocket, not insurance.', 'Health already takes nearly a tenth of household spending, so every increase hurts.'] },
      { slug: 'why-school-fees-make-education-costs-jump-once-a-year',
        articleTitle: "Why School Fees Make Education Costs Jump Once a Year",
        hook: 'School costs don’t creep up — they jump once a year, all at once.',
        points: ['School costs rose 3%', 'All in one jump', 'Once a year'],
        bodies: ['For parents, school costs rose 3.2% — but not little by little.', 'Because fees are set once a year, the whole increase lands in a single term.', 'That one big bill is why school season strains so many households at once.'] },
      { slug: 'the-one-bill-that-s-getting-cheaper-phone-and-data',
        articleTitle: "The One Bill That's Getting Cheaper: Phone and Data",
        hook: 'One bill is actually getting cheaper — your phone and data.',
        points: ['Phone and data got cheaper', 'Down 5% in a year', 'One bill actually falling'],
        bodies: ['For anyone who buys scratch cards or data, phone costs fell 5.0% over the year.', 'It’s one of the very few bills actually going down.', 'Competition between networks is quietly handing users a small break.'] },
      { slug: 'taxpayers-not-donors-are-now-funding-the-budget',
        articleTitle: "Taxpayers, Not Donors, Are Now Funding the Budget",
        hook: 'The country is now paying for itself — donor grants read zero.',
        points: ['The country funds itself now', 'About US$60 million a month', 'Donor grants read zero'],
        bodies: ['For citizens, the budget now leans on the taxes people and businesses pay — US$187 million in three months.', 'That’s a steady near-US$60 million a month.', 'Recorded donor grants were zero, so the country is increasingly paying its own way.'] },
      { slug: 'the-public-payroll-eats-a-large-slice-of-the-budget',
        articleTitle: "The Public Payroll Eats a Large Slice of the Budget",
        hook: 'Before a single road is built, the government payroll takes its cut.',
        points: ['Salaries take the biggest slice', 'US$40.5 million in a month', 'Less left for roads'],
        bodies: ['For anyone waiting on a new road or clinic, government salaries eat the largest share of spending.', 'They hit US$40.5 million in a single month.', 'Every dollar on payroll is one not spent building the things communities need.'] },
      { slug: 'running-costs-crowd-out-investment-in-the-national-budget',
        articleTitle: "Running Costs Crowd Out Investment in the National Budget",
        hook: 'The budget pays the bills but has almost nothing left to build with.',
        points: ['Little left to build with', 'Investment near zero for months', 'Then one US$50M push'],
        bodies: ['For communities awaiting roads and water, the government invested almost nothing for months.', 'A single US$50 million push landed in March, then it went quiet again.', 'Day-to-day running costs swallow the budget, leaving little for what growth depends on.'] },
      { slug: 'government-spending-lurches-month-to-month-bunching-at-year-end',
        articleTitle: "Government Spending Lurches Month to Month, Bunching at Year-End",
        hook: 'Some months the government spends little; others, six times as much.',
        points: ['Spending swings wildly', 'US$33M one month, US$193M another', 'Hard to plan around'],
        bodies: ['For a contractor who supplies the state, payments arrive in fits and starts.', 'The government spent US$33 million one month and nearly six times that in another.', 'Those swings make it hard for anyone doing business with the state to plan.'] },
      { slug: 'a-building-boom-pushes-construction-past-us-270-million',
        articleTitle: "A Building Boom Pushes Construction Past US$270 Million",
        hook: 'Every new building site adds up to a US$270 million boom.',
        points: ['Building is booming', 'US$270 million of work', 'Nearly double 2020'],
        bodies: ['For masons, laborers and hardware sellers, construction hit US$270 million of work.', 'That’s about 9% more than last year.', 'And nearly double 2020 — one of the clearest signs of money going into buildings.'] },
      { slug: 'moving-people-and-data-grows-into-a-us-257-million-business',
        articleTitle: "Moving People and Data Grows Into a US$257 Million Business",
        hook: 'Getting people, goods and data around quietly became a big earner.',
        points: ['Moving people and data grew', 'Now US$257 million', 'Mobile and logistics led'],
        bodies: ['For drivers, dispatch riders and phone users, transport and communications grew about 8%.', 'Together the sector is worth US$257 million.', 'Mobile services and moving goods around did most of the lifting.'] },
      { slug: 'more-power-flows-yet-few-are-still-connected',
        articleTitle: "More Power Flows, yet Few Are Still Connected",
        hook: 'More power is flowing than ever — yet most homes still aren’t connected.',
        points: ['More power is flowing', 'Up about 31%', 'Yet few are connected'],
        bodies: ['For households still on generators and candles, power generation rose 30.7% over the year.', 'The power-and-water sector grew to US$50 million.', 'Yet most homes still aren’t on the grid, so the gains haven’t reached everyone.'] },
      { slug: 'homegrown-steel-output-more-than-doubles-in-a-year',
        articleTitle: "Homegrown Steel Output More Than Doubles in a Year",
        hook: 'The steel in new buildings is increasingly made right here.',
        points: ['Local steel more than doubled', 'Up to 4,267 tonnes', 'Made right here'],
        bodies: ['For builders buying rods and beams, more of the steel is now made locally.', 'Output more than doubled to 4,267 tonnes in a year.', 'That means less reliance on imported building materials.'] },
      { slug: 'rice-the-us-296-million-staple-with-outsized-political-weight',
        articleTitle: "Rice: The US$296 Million Staple With Outsized Political Weight",
        hook: 'No single food carries more political weight than the rice in your pot.',
        points: ['Rice is the big staple', 'Worth about US$296 million', 'And politically charged'],
        bodies: ['For every household, rice is the daily staple — worth about US$296 million last year.', 'That’s down from US$350 million the year before.', 'With so much still imported, its price stays one of the country’s touchiest issues.'] },
      { slug: 'the-state-s-own-economic-output-barely-grew-last-year',
        articleTitle: "The State's Own Economic Output Barely Grew Last Year",
        hook: 'The part of the economy the government itself runs barely moved.',
        points: ['Government output barely grew', 'Up under 3%', 'Slowest major sector'],
        bodies: ['For those who rely on public services, the state’s own output grew just 2.7%.', 'It was worth US$169 million.', 'A tight budget and heavy wage bill leave little room for it to expand.'] },
      { slug: 'bottlers-ramp-up-20-as-consumer-spending-holds',
        articleTitle: "Bottlers Ramp Up 20% as Consumer Spending Holds",
        hook: 'The drinks on your shop shelf say people are still spending.',
        points: ['Drink-making jumped 20%', 'Up to 4.0 million liters', 'People are still spending'],
        bodies: ['For shopkeepers stocking soft drinks, local production jumped 20.3% over the year.', 'Output reached 4.0 million liters.', 'That people keep buying is a sign spending is holding up.'] },
    ],
  },
  {
    category: 'Business',
    hooks: [
      { slug: 'cost-of-credit-liberian-business-borrowing',
        articleTitle: "The Cost of Credit: Why Liberian Businesses Pay 13% to Borrow",
        hook: 'A cookshop owner borrows L$500,000. The interest alone is over L$65,000 a year.',
        points: ['Loans cost 13.11%', 'L$65,000 a year on L$500,000', 'Before you repay a cent'],
        bodies: ['For a cookshop owner borrowing L$500,000 to open a second spot, interest alone tops L$65,000 a year.', 'That’s the 13.11% rate at work — money owed whether or not the new spot succeeds.', 'And it’s all due before she pays back a single cent of the loan itself.'] },
      { slug: 'cbl-holds-policy-rate-16-25-what-businesses-know',
        articleTitle: "CBL Holds Policy Rate at 16.25% — What Businesses Should Know",
        hook: 'The Central Bank is holding rates at 16.25% — here’s what it means for your loan.',
        points: ['Rates are staying put', 'Held at 16.25%', 'So loans stay pricey'],
        bodies: ['For a business owner hoping for cheaper credit, the Central Bank kept its rate at 16.25%.', 'It’s down from 20% in 2024, but still high.', 'So a business loan still costs around 13% — don’t count on it easing soon.'] },
      { slug: 'government-revenue-surges-march-2026',
        articleTitle: "Government Revenue Hits US$304 Million in March — What It Means for Businesses That Sell to the State",
        hook: 'For anyone who sells to the government, US$304 million just moved.',
        points: ['The state collected US$304M', 'A big month', 'But it pays in bursts'],
        bodies: ['For a supplier who sells to government, US$304.37 million flowed into state coffers in March.', 'That means there’s money to pay contractors — when the state chooses to.', 'But its income comes in bursts, so being paid on time is never a given.'] },
      { slug: 'personal-loans-hidden-tax-informal-entrepreneurs',
        articleTitle: "Personal Loans Cost 16.16% — The Hidden Tax on Informal Entrepreneurs",
        hook: 'Borrow as a person, not a business, and you pay a hidden penalty.',
        points: ['Personal loans cost 16.16%', '3 points above businesses', 'A penalty for being informal'],
        bodies: ['For a market trader who borrows in her own name, the rate is 16.16%.', 'That’s three full points above the 13.11% a registered business pays.', 'Staying informal quietly costs her more every time she borrows.'] },
      { slug: 'record-imports-small-retailer-impact-march-2026',
        articleTitle: "A US$314 Million Import Bill: What a Two-Year High Means for Small Retailers",
        hook: 'A flood of US$314 million in goods just landed — cheaper prices aren’t guaranteed.',
        points: ['A flood of goods landed', 'US$314 million in a month', 'Cheaper prices aren’t promised'],
        bodies: ['For a small retailer in Red Light, a record US$314.08 million of goods poured in during March.', 'Bigger importers can stock deep and price low.', 'So more supply can squeeze a small trader’s margin instead of widening it.'] },
      { slug: 'fuel-cost-jump-small-business-impact-march-2026',
        articleTitle: "Fuel Costs Jump 12% in One Month — Headline Inflation Reads 0.6%",
        hook: 'Keke driver, your fuel jumped 12% in a month — the news said prices barely moved.',
        points: ['Fuel jumped 12% in a month', 'The news said prices barely moved', 'Your day says otherwise'],
        bodies: ['For a keke driver, fuel jumped 12.38% in a single month.', 'Yet the official inflation figure read just 0.62%.', 'When fuel is your biggest cost, that average simply doesn’t describe your day.'] },
      { slug: 'rubber-production-drop-smallholder-impact-march-2026',
        articleTitle: "Rubber Output Drops 47% as Smallholder Farmers Bear the Cost",
        hook: 'Rubber farmer, your trees gave nearly half as much this month — so did your pay.',
        points: ['Rubber output nearly halved', 'Down to 3,476 tonnes', 'Pay drops the same'],
        bodies: ['For a smallholder rubber farmer, the trees gave nearly half as much this month.', 'Output fell from 6,527 tonnes to 3,476.', 'Paid by weight, his income dropped just as sharply — with no cushion to fall back on.'] },
      { slug: 'liberia-5-billion-economy-sectoral-breakdown',
        articleTitle: "Where the US$5.2 Billion Economy Really Comes From",
        hook: 'Where does a US$5.2 billion economy actually come from?',
        points: ['A US$5.2 billion economy', 'Services lead it', 'Then farming'],
        bodies: ['For anyone wondering where the money is, the economy is worth about US$5.2 billion.', 'Services — shops, transport, hotels — are the biggest slice at 38.7%.', 'Farming is next at 28.7%, still central to how most people earn.'] },
      { slug: 'trade-hospitality-sector-services-boom',
        articleTitle: "Trade and Hospitality Sector Hits US$506 Million — Inside the Quiet Services Boom",
        hook: 'Shops, hotels and restaurants quietly became a US$506 million business.',
        points: ['Shops and hotels hit US$506M', 'Up 5.5%', 'A third of services'],
        bodies: ['For traders and hotel workers, buying, selling and hosting grew to US$505.74 million.', 'That’s about 5.5% more than last year.', 'It now makes up a third of the whole services economy.'] },
      { slug: 'china-buys-134-million-liberian-exports-2025',
        articleTitle: "China Buys US$134 Million of Liberian Exports After Near-Zero in 2024",
        hook: 'China went from buying almost nothing to US$134 million of our goods.',
        points: ['China is buying big again', 'US$134 million of exports', 'From almost nothing'],
        bodies: ['For miners and exporters, China went from buying almost nothing to US$134.19 million.', 'A year earlier the figure was under a million dollars.', 'It looks like the return of a big buyer last seen back in 2014.'] },
      { slug: 'banks-hold-260-billion-deposits-where-goes-money',
        articleTitle: "Banks Hold L$260 Billion in Deposits — Where Does the Money Go?",
        hook: 'Banks are holding L$260 billion of deposits. Where does it all go?',
        points: ['Banks hold L$260 billion', 'About US$1.4 billion', 'But barely lend it out'],
        bodies: ['For a business seeking a loan, banks are sitting on about L$260 billion in deposits.', 'That’s roughly US$1.4 billion of money.', 'Yet lending to business grew just 1.1% — the money mostly stays put.'] },
      { slug: 'rubber-output-106-million-uneven-recovery',
        articleTitle: "Rubber Hits US$106 Million in GDP but Monthly Output Swings Wildly",
        hook: 'Rubber earned US$106 million last year — while lurching wildly month to month.',
        points: ['Rubber earned US$106 million', 'Up 8% for the year', 'But wildly up and down'],
        bodies: ['For rubber-farming families, the crop was worth about US$106 million last year, up 8%.', 'But month to month, output swung from 14,214 tonnes down to 1,871.', 'So the sector grows in value while whipsawing households season to season.'] },
      { slug: 'liberian-startups-barriers-first-year',
        articleTitle: "Why Most Liberian Startups Never Get Past the First Year",
        hook: 'The economy grew 4.57% — so why do most new businesses die in year one?',
        points: ['The economy grew 4.57%', 'Yet startups still fail fast', 'Credit and costs block them'],
        bodies: ['For a young founder, the economy grew a healthy 4.57% — but starting up is still brutal.', 'Loans are dear and hard to get.', 'Costly imported inputs and a small market make it hard to survive past year one.'] },
    ],
  },
  {
    category: 'Banking',
    hooks: [
      { slug: 'money-supply-299-billion-composition-shift-march-2026',
        articleTitle: "Money Supply Hits L$299 Billion — Why Cash Is Up and Savings Are Down",
        hook: 'Susu member, there’s more cash around but savings in the bank are shrinking.',
        points: ['More cash is around', 'But savings are shrinking', 'The bank is still safer'],
        bodies: ['For a susu member, there’s 10.66% more money in the economy than a year ago.', 'Yet money kept in savings actually fell 6.51% — people are holding cash instead.', 'Still, cash at home loses value as prices rise; in the bank it stays safer and grows a little.'] },
      { slug: 'banks-are-lending-to-the-government-not-to-business',
        articleTitle: "Banks Are Lending to the Government, Not to Business",
        hook: 'Your loan is hard to get because the bank prefers a safer borrower: the state.',
        points: ['Your loan is hard to get', 'Business lending rose just 1.1%', 'The state gets the credit'],
        bodies: ['For a business owner, credit barely grew — up just 1.1%, a fall once you count rising prices.', 'Meanwhile lending to government jumped about 40%.', 'Banks prefer the safer borrower, so your loan sits at the back of the queue.'] },
      { slug: 'business-loans-get-pricier-even-as-consumer-rates-fall',
        articleTitle: "Business Loans Get Pricier Even as Consumer Rates Fall",
        hook: 'Business loans got dearer this year even as personal loan rates eased.',
        points: ['Business loans got dearer', 'Now 13.11%', 'Savers still earn 1.94%'],
        bodies: ['For a firm borrowing to grow, the loan rate crept up to 13.11% this year, from 12.25%.', 'Personal and mortgage rates eased, but business rates did not.', 'And savers still earn just 1.94%, so the bank’s margin stayed wide.'] },
      { slug: 'the-financial-sector-keeps-growing-but-not-by-lending-to-business',
        articleTitle: "The Financial Sector Keeps Growing — but Not by Lending to Business",
        hook: 'Banks are growing nicely — just not by lending to business.',
        points: ['Banks keep growing', 'Now US$161 million', 'Just not by lending to you'],
        bodies: ['For a business, banks and finance firms grew nicely to US$161 million.', 'But their lending leaned toward government, not business.', 'So the sector expands faster than the credit actually reaching ordinary firms.'] },
      { slug: 'cash-outside-banks-jumped-22-in-liberia-as-deposits-grew-slowly',
        articleTitle: "Cash Outside Banks Jumped 22% in Liberia as Deposits Grew Slowly",
        hook: 'More people are keeping cash at home than trusting it to the bank.',
        points: ['Cash at home jumped 22%', 'Faster than deposits', 'A drag on everyone'],
        bodies: ['For many earners, keeping cash at home rose 22% — outpacing money put in banks.', 'Much daily activity stays informal, done hand to hand in cash.', 'But money under the mattress is money banks can’t lend on, so credit stays tight for all.'] },
    ],
  },
  {
    category: 'Markets',
    hooks: [
      { slug: 'banking-spread-13-percent-lending-2-percent-savings-feb-2026',
        articleTitle: "13.11% to Borrow, 1.94% to Save: the Spread That Shapes Every Investment",
        hook: 'The bank charges you 13.11% to borrow and pays you 1.94% to save.',
        points: ['You borrow at 13.11%', 'You save at just 1.94%', 'The bank keeps the gap'],
        bodies: ['For a cookshop owner taking a loan, credit costs 13.11% a year — real money before any profit.', 'For a susu member saving small, the bank pays just 1.94%, and rising prices eat most of that.', 'The 11.17-point gap in between is the bank’s cut, paid by saver and borrower alike.'] },
    ],
  },
  {
    category: 'Forex',
    hooks: [
      { slug: 'exchange-rate-8-percent-shift-business-impact',
        articleTitle: "From L$200 to L$184: How an 8% Currency Swing Is Reshaping Margins",
        hook: 'The US dollar went from L$200 to L$184 in a year — that splits every business.',
        points: ['The dollar fell to L$184', 'From L$200 a year ago', 'It splits every business'],
        bodies: ['For an importer, the US dollar now costs about L$184, down from L$200 — goods land cheaper.', 'For a gold miner or anyone earning dollars, the same move means fewer L$ per dollar.', 'So the stronger L$ helps one side of the counter and hurts the other.'] },
      { slug: 'a-stronger-currency-eases-import-costs-as-the-us-dollar-slips-to-l-184',
        articleTitle: "A Stronger Currency Eases Import Costs as the US Dollar Slips to L$184",
        hook: 'A stronger L$ is quietly making imported goods cheaper at the port.',
        points: ['A stronger L$', 'Imports cost a bit less', 'Held up by gold and family abroad'],
        bodies: ['For a shopkeeper buying abroad, the L$ at about 184 to the dollar makes imports a little cheaper.', 'Booming gold sales and money from family abroad are holding it up.', 'It has slipped a little since late last year, so it’s worth keeping an eye on.'] },
    ],
  },
  {
    category: 'Commodities',
    hooks: [
      { slug: 'gold-export-concentration-risk-march-2026',
        articleTitle: "Gold Hit US$175 Million in March — Now Two-Thirds of All Exports",
        hook: 'Two-thirds of everything the country sells abroad is now just gold.',
        points: ['Gold is two-thirds of exports', 'US$175 million in a month', 'A risky bet on one price'],
        bodies: ['For the whole country, gold now earns two-thirds of everything sold abroad — US$175.13 million in March.', 'Add iron ore and just two metals are 92.59% of exports.', 'That steadies the dollar in your pocket today, but leaves everyone exposed if gold prices fall.'] },
      { slug: 'gold-overtakes-iron-ore-as-liberia-s-top-export-earner-at-us-175m',
        articleTitle: "Gold Overtakes Iron Ore as Liberia's Top Export Earner at US$175m",
        hook: 'For the first time, gold — not iron ore — is the country’s top earner abroad.',
        points: ['Gold is now the top earner', 'US$175 million', 'Past iron ore for the first time'],
        bodies: ['For the export economy, gold has overtaken iron ore as the biggest earner abroad.', 'It brought in US$175 million, more than double a year earlier.', 'With output near 38,000 ounces, gold now shapes the whole trade picture.'] },
      { slug: 'exports-surge-58-to-us-2-1-billion-powered-by-gold',
        articleTitle: "Exports Surge 58% to US$2.1 Billion, Powered by Gold",
        hook: 'The country sold US$2.07 billion abroad last year — gold did the heavy lifting.',
        points: ['Exports hit US$2.07 billion', 'Gold led the way', 'But imports were bigger'],
        bodies: ['For the country, exports jumped nearly 58% to US$2.07 billion, powered by gold.', 'But imports were bigger still at US$2.35 billion.', 'So even in a boom year, the country buys more than it sells.'] },
      { slug: 'iron-ore-output-rebounds-to-2-3-million-tonnes-in-march',
        articleTitle: "Iron-Ore Output Rebounds to 2.3 Million Tonnes in March",
        hook: 'After a weak stretch, iron ore came back to 2.3 million tonnes in a month.',
        points: ['Iron ore came back strong', '2.3 million tonnes in a month', 'Earnings up 47%'],
        bodies: ['For mining towns, iron-ore output rebounded to 2.33 million tonnes in the month.', 'Earnings rose 47% to US$69 million.', 'But volumes swing with demand for steel abroad, so the work can be uneven.'] },
      { slug: 'cement-output-hits-a-record-as-the-building-boom-rolls-on',
        articleTitle: "Cement Output Hits a Record as the Building Boom Rolls On",
        hook: 'Every bag of cement is at a record high — the building boom is real.',
        points: ['Cement hit a record', '89,000 tonnes', 'Up 52% on the year'],
        bodies: ['For builders and cement sellers, output hit a record 89,000 tonnes.', 'That’s up 52.5% on the year.', 'It’s a clear sign the building boom is real and still rolling on.'] },
      { slug: 'gold-and-iron-ore-drive-mining-higher-as-rubber-falls',
        articleTitle: "Gold and Iron Ore Drive Mining Higher as Rubber Falls",
        hook: 'Dig it up and it’s booming; grow it and it’s falling.',
        points: ['Dig it up, it’s booming', 'Grow it, it’s falling', 'Two different economies'],
        bodies: ['For miners, diamonds more than doubled and cement rose over 50%.', 'For farmers, rubber, cocoa and timber all slipped.', 'One economy digs and races ahead; the other grows and lags behind.'] },
      { slug: 'palm-oil-rebounds-to-us-173-million-after-volatile-years',
        articleTitle: "Palm Oil Rebounds to US$173 Million After Volatile Years",
        hook: 'Palm oil is bouncing back to US$173 million after shaky years.',
        points: ['Palm oil is bouncing back', 'Worth about US$173 million', 'Above pre-pandemic'],
        bodies: ['For palm growers, the crop rebounded to about US$173 million last year.', 'That’s nearly 9% more than the year before.', 'And well above its 2020 level — a real recovery after shaky years.'] },
      { slug: 'palm-oil-jumps-diamonds-double-cocoa-slumps-in-liberia-s-march-commodity-mix',
        articleTitle: "Palm Oil Jumps, Diamonds Double, Cocoa Slumps in Liberia's March Commodity Mix",
        hook: 'In one month palm oil rose, diamonds doubled, and cocoa collapsed.',
        points: ['A mixed month', 'Palm oil and diamonds up', 'Cocoa collapsed'],
        bodies: ['For smallholders, the smaller crops pulled in different directions in March.', 'Palm-oil sales rose to US$6.6 million and diamonds more than doubled.', 'But cocoa fell more than half, a reminder how fragile diversifying beyond gold still is.'] },
      { slug: 'vast-forests-idle-trade-why-forestry-is-stuck',
        articleTitle: "Vast Forests, Idle Trade: Why Forestry Is Stuck",
        hook: 'The country is covered in forest — yet timber trade sits near zero.',
        points: ['Forests everywhere', 'Yet timber trade is idle', 'Only US$18 million'],
        bodies: ['For forest communities, logging was worth just US$18 million despite vast woodland.', 'That’s below its 2020 level.', 'Recorded round-log output was zero — a huge resource sitting idle while jobs go unmade.'] },
    ],
  },
  {
    category: 'Technology',
    hooks: [
      { slug: 'ekan-connect-fintech-messaging',
        articleTitle: "EKAN Connect Wants to Turn Every Chat Into a Checkout",
        hook: 'What if you got paid inside the same chat where you close the deal?',
        points: ['Pay inside your chats', 'Built for WhatsApp traders', 'A huge market coming'],
        bodies: ['For a trader who sells over WhatsApp, a Liberian startup wants payments built right into the chat.', 'No more screenshotting invoices or sharing account numbers with strangers.', 'Africa’s digital payments are projected past US$40 billion by 2028 — a big prize to chase.'] },
      { slug: 'monrovia-hustle-liberia-open-world-game',
        articleTitle: "Monrovia Hustle: A Liberian Studio's Bet That West Africa Can Build a Global Video Game",
        hook: 'A full open-world game of Monrovia — built solo on a 4 GB laptop.',
        points: ['A game set in Monrovia', 'Built on a 4 GB laptop', 'A pitch to investors'],
        bodies: ['For local creators, one person built a playable open-world game set in downtown Monrovia.', 'The whole thing ran on a modest 4 GB laptop.', 'It’s a calculated pitch to investors — proof of what’s possible from here.'] },
      { slug: 'huix-2099-monrovia-studio-profile',
        articleTitle: "Inside HUIX-2099: The Monrovia Studio Building VR, AI and 3D Products for a Global Market",
        hook: 'One person in Monrovia, five shipped products, building for the world.',
        points: ['A one-person Monrovia studio', 'Five products shipped', 'Building for the world'],
        bodies: ['For aspiring founders, a single person in Monrovia started a tech studio back in 2024.', 'It has already shipped five products.', 'That pace — from a market with no venture scene — is rare anywhere in the world.'] },
      { slug: 'african-game-development-digital-economy',
        articleTitle: "What a Liberian Open-World Game Says About the Future of African Digital Content",
        hook: 'Games are a US$184 billion industry — almost none of it made in West Africa.',
        points: ['Games are a US$184B industry', 'Almost none from here', 'A wide-open door'],
        bodies: ['For young Liberian coders, video games are a US$184 billion business worldwide.', 'It’s bigger than film and music combined.', 'Almost none of it is made in West Africa — which makes it a wide-open door.'] },
    ],
  },
  {
    category: 'Analytics',
    hooks: [
      { slug: 'mining-output-tops-us-1-billion-driving-one-fifth-of-liberia-s-gdp',
        articleTitle: "Mining Output Tops US$1 Billion, Driving One-Fifth of Liberia's GDP",
        hook: 'Mining alone is now worth over US$1 billion — a fifth of the whole economy.',
        points: ['Mining passed US$1 billion', 'A fifth of the economy', 'The engine of growth'],
        bodies: ['For the country, the value dug from the mines passed US$1 billion, up 23%.', 'That’s about a fifth of the whole economy.', 'It was the single biggest reason the economy grew last year — but few people work there.'] },
      { slug: 'a-two-speed-economy-minerals-race-ahead-most-people-don-t',
        articleTitle: "A Two-Speed Economy: Minerals Race Ahead, Most People Don't",
        hook: 'The mines are racing ahead while most people are left behind.',
        points: ['Two economies, two speeds', 'Mines race ahead', 'Most people don’t'],
        bodies: ['For most Liberians, the mines raced past US$1 billion while farming grew barely 1%.', 'The gains pile up where only a few people work.', 'Those two speeds decide who really shares in the country’s growth.'] },
      { slug: 'lumpy-taxes-volatile-spending-rising-debt-the-2026-budget',
        articleTitle: "Lumpy Taxes, Volatile Spending, Rising Debt: The 2026 Budget",
        hook: 'The 2026 budget runs on lumpy taxes, uneven spending and rising debt.',
        points: ['Lumpy taxes, uneven spending', 'Debt over US$2.8 billion', 'Little room to spare'],
        bodies: ['For the budget, tax income is uneven — spiking to US$304 million in March, thin in other months.', 'Spending jumps around just as much.', 'And debt past US$2.8 billion leaves the country little room to spare when trouble hits.'] },
      { slug: 'a-rare-current-account-surplus-at-least-by-the-central-bank-s-count',
        articleTitle: "A Rare Current-Account Surplus, at Least by the Central Bank's Count",
        hook: 'By one count the country ran a rare surplus — by another, a deficit.',
        points: ['A rare surplus — or not', 'Family abroad held it up', 'Depends who counts'],
        bodies: ['For the external accounts, the Central Bank counted a rare surplus of about US$77 million.', 'Money from family abroad — US$941 million — kept it in the black.', 'Measured another way, the World Bank sees a deficit instead: same year, two answers.'] },
      { slug: 'imported-goods-hold-steady-it-s-local-prices-that-are-rising',
        articleTitle: "Imported Goods Hold Steady; It's Local Prices That Are Rising",
        hook: 'It’s not imported goods driving prices up — it’s home-grown costs.',
        points: ['It’s not imports this time', 'Home-grown prices rose', 'The usual story flipped'],
        bodies: ['For a shopper, imported goods barely moved in price over the year, up just 0.1%.', 'It was home-grown prices that rose almost 6%.', 'So this time the pressure is local, not from abroad — the opposite of the usual story.'] },
      { slug: 'incomes-per-person-are-still-climbing-back-to-2018-levels',
        articleTitle: "Incomes Per Person Are Still Climbing Back to 2018 Levels",
        hook: 'The economy is growing, but the average person still earns less than in 2018.',
        points: ['Incomes are creeping up', 'Still below 2018', 'Population eats the gains'],
        bodies: ['For the average person, income rose about 2.4% last year.', 'It’s recovered 12.5% from the 2020 low.', 'But it still sits below 2018 — a growing population eats into the headline gains.'] },
    ],
  },
];
